### ISSUE TITLE
Configmap variable removal not resetting value immediately

### ISSUE THREAD

**Issue by afugazzotto** [numaproj-labs/numaplane#189]
**Describe the bug**
When removing the LogLevel variable from configmap, it takes 1 or more iterations for the variable to be reset to zero. This could impact also other variables (not only the LogLevel).

**To Reproduce**

1. add logLevel with a valid non-zero value (ex: 4 = debug) to the configmap using `kubectl edit`;
2. the logger should start showing appropriate logs based on level (ex: debug messages);
3. while tailing the logs, use `kubectl edit` to remove the logLevel variable from the configmap;
4. the variable value will not change to zero for 1 or more cycles, then it will change to zero.

**Expected behavior**
When removing the variable from configmap, the value should be applied immediately.

---

**Message from the maintainers**:

Impacted by this bug? Give it a 👍. We often sort issues this way to know what to prioritize.

**Comment by juliev0** [comment]
As far as this bug, I'm kind of wondering if it's reasonable for there to be a delay when re-reading the ConfigMap? And that if someone wants immediacy then they should restart the Pod? 

But it's true that we should revisit our general strategy when it comes to re-ingesting the ConfigMap and see if there are improvements that can be made.

I think by "iteration"/"cycle", you mean where the re-ingestion is happening [here](https://github.com/numaproj-labs/numaplane/blob/main/internal/sync/syncer.go#L221-L226) each time `runOnce()` is called? The only way to have immediacy would be for the Log functions - `Info()`, `Debug()` -  to reference directly the global config each time when logging. 

Background: The way we wrote the ConfigMap logic, we wanted to have thread safety because there's a separate [thread](https://github.com/numaproj-labs/numaplane/blob/main/internal/controller/config/config.go#L74) which does the write. 
There are 2 potential issues: 1. let's say a reader is only interested in one field - well, at least that one field that they read should be safe to read. 2. let's say a reader is interested in more than one field - that combination of fields should also be atomically correct. 

I guess the current limitation is that we need to make sure that every long-running thread needs to proactively call `controllerConfig.GetConfigManagerInstance().GetConfig()` each time it wants the latest and greatest info. 

Theoretically, for readers who only need one variable and thus don't need atomic correctness between two variables (like the logger), they could reference `controllerConfig.GetConfigManagerInstance().GetConfig().LogLevel` directly, but this is currently an expensive call, as there's an entire cloning of the ConfigMap through [json serialization/deserialization](https://github.com/numaproj-labs/numaplane/blob/main/internal/controller/config/config.go#L88) (which could theoretically be replaced by a deep copy and probably less expensive but still somewhat expensive). 

For readers who only need one variable at one moment in time, they could be fine to read directly from `cm.config` as long as they're protected by a Read Lock:
```
func (cm *ConfigManager) GetConfig() (*GlobalConfig, error) {
	cm.lock.RLock()
	defer cm.lock.RUnlock()
	return cm.config, nil
}
...
doSomething( config.GetConfigManagerInstance().GetConfig().LogLevel )
```

For readers who need atomic correctness between multiple fields, they would still want to get a copy of the Config:
```
func (cm *ConfigManager) GetConfig() (GlobalConfig, error) {
	cm.lock.RLock()
	defer cm.lock.RUnlock()
	config, err := CloneWithSerialization(cm.config) // or DeepCopy
	if err != nil {
		return GlobalConfig{}, err
	}
	return *config, nil
}
```

**Comment by juliev0** [comment]
One thing we noticed yesterday is that because `numaLogger.SetLevel(globalConfig.LogLevel)` is only in the Syncer code, that if there's no Git repo being synced but the Reconciler is being called, the reconciler goroutine will remain at its existing log level.

**Comment by juliev0** [comment]
@afugazzotto I just noticed that in [this](https://github.com/numaproj-labs/numaplane/pull/177/files) PR, there are lines like this:
```
numaLogger := logger.FromContext(ctx)
```
but context never gets updated to include the logger with the new log level.

**Comment by chandankumar4** [comment]
While debugging find out that [OnConfigChange()](https://github.com/numaproj-labs/numaplane/blob/1da9fcc1ab83112f0c35781d443fa039843a8207/internal/controller/config/config.go#L75) method is one who is responsible for updating the global configmap value and I noticed that it's not detecting the changes instantly and taking around 2-5sec which is weird, so I'm going through the implementation of this method to found out more. 

Also found more reference [here](https://ahmet.im/blog/kubernetes-secret-volumes-delay/) not sure it's linked with it.

**Comment by chandankumar4** [comment]
I have confirmed this issue after debugging further that it's not with out code, it's related to configmap sync issue with pod, an issue is linked with it [here](https://github.com/kubernetes/kubernetes/issues/30189) 
A possible approach is given [here](https://github.com/kubernetes/kubernetes/issues/30189#issuecomment-868790895) which I have tried and it's working.

@xdevxy @juliev0 what do you think?
