### ISSUE TITLE
Support for manifest managed by Kustomize

### ISSUE THREAD

**Issue by xdevxy** [numaproj-labs/numaplane#24]
In the case the manifest is managed by Kustomize, we may want to spawn Kustomize as subprocess and dynamically build the YAML file and apply the resources accordingly. In this way we can handle both Kustomize managed and non-managed case smoothly. To be able to detect the change, we can provide a default option to build the YAML files each time we sync (e.g every 3 mins) and compare if there are any changes in the end result manifests.

**Comment by juliev0** [comment]
@chandankumar4 can you describe the approach/design once you've determined it?

**Comment by chandankumar4** [comment]
Here's the approach I have came up with!!
1. Check the repo is kustomize enabled or not, by checking - If any of this file present in the root dir `kustomization.yaml`, `kustomization.yml` or `Kustomization`. or by taking input from user.
2. Generate the kustomized manifest using library: https://github.com/kubernetes-sigs/kustomize
3. Apply the generated manifest

Please add anything If i miss something!!!

**Comment by juliev0** [comment]
> 1. Check the repo is kustomize enabled or not, by checking - If any of this file present in the root dir `kustomization.yaml`, `kustomization.yml` or `Kustomization`. or by taking input from user.

when you say "taking input from user", do you mean adding a field to the `RepositoryPath` in the CRD? I feel like we can have a `type` field which could be set to `kustomize` or `raw`. As for whether we should also check if there's a file in there called "kustomization.yaml" if they don't set the `type` - I'm thinking we would also need to re-check repeatedly if all of a sudden they change it so that there is one of those files all of a sudden, or they change it so there isn't. I tend to think just asking them to be explicit could make the most sense? Let me know if you disagree, though.

> 2. Generate the kustomized manifest using library: https://github.com/kubernetes-sigs/kustomize

If there is a reference to another repo, will it work to use this? (I'm also thinking about how theoretically we could be _continually_ monitoring any external repos that are referenced, but that could also be something done later. Maybe starting simple is best.)

In your design does the [Path](https://github.com/numaproj-labs/numaplane/blob/main/api/v1alpha1/gitsync_types.go#L82) refer to the root directory? Also, we need to make sure this works if a reference is farther up from the root directory (example of a kustomization.yaml [here](https://github.intuit.com/kubernetes/cluster-deployments/blob/master/src/numaflow/base/v1.1.5/kustomization.yaml) which has that). I'm not sure if this code will get replaced or not, but right now we check out a given Tree at a [path](https://github.com/numaproj-labs/numaplane/blob/main/internal/git/gitsync_processor.go#L252).

**Comment by chandankumar4** [comment]
> when you say "taking input from user", do you mean adding a field to the RepositoryPath in the CRD? I feel like we can have a type field which could be set to kustomize or raw. As for whether we should also check if there's a file in there called "kustomization.yaml" if they don't set the type - I'm thinking we would also need to re-check repeatedly if all of a sudden they change it so that there is one of those files all of a sudden, or they change it so there isn't. I tend to think just asking them to be explicit could make the most sense? Let me know if you disagree, though.

Yes I was thinking to add a field to RepositoryPath CRD but asking user explicitly might be an extra overhead as anyhow we have to check each time that  `kustomization.yaml` is present or not, if they suddenly add/remove it.

**Comment by chandankumar4** [comment]
>In your design does the [Path](https://github.com/numaproj-labs/numaplane/blob/main/api/v1alpha1/gitsync_types.go#L82) refer to the root directory? Also, we need to make sure this works if a reference is farther up from the root directory (example of a kustomization.yaml [here](https://github.intuit.com/kubernetes/cluster-deployments/blob/master/src/numaflow/base/v1.1.5/kustomization.yaml) which has that). I'm not sure if this code will get replaced or not, but right now we check out a given Tree at a [path](https://github.com/numaproj-labs/numaplane/blob/main/internal/git/gitsync_processor.go#L252), so whatever we check out needs to include all of those dependencies.

yes, Path is root directory of the repo where kustomization file is present. for example, path can be [namespace-install](https://github.com/numaproj/numaflow/tree/main/config/namespace-install) here and this `kustomization` file is referencing the previous dir as for [base](https://github.com/numaproj/numaflow/blob/main/config/namespace-install/kustomization.yaml#L5)

**Comment by juliev0** [comment]
> > Yes I was thinking to add a field to RepositoryPath CRD but asking user explicitly might be an extra overhead as anyhow we have to check each time that kustomization.yaml is present or not, if they suddenly add/remove it.

You're right that we do need to find the file regardless. I guess you probably already looked this up, but I just verified that only "kustomization.yaml" and "kustomization.yml" are the only allowed file names - I thought maybe you could have something more custom. This is why I was originally thinking the CRD would include a `KustomizationFilePath` field, but maybe this isn't necessary. I wonder if we may not need a `Type` field at all. 

I guess it all comes down to the question: do we insist that people only store the files that they want to deploy in their RepositoryPaths? If so, then it does seem like we don't need the `Type` field, and we can just basically determine if there's a kustomization.yaml/yml there. I'm okay if we go this route. (Note, we may want to add a field later if it turns out we need it for Helm distinction.) cc @xdevxy 

> yes, Path is root directory of the repo where kustomization file is present. for example, path can be [namespace-install](https://github.com/numaproj/numaflow/tree/main/config/namespace-install) here and this `kustomization` file is referencing the previous dir as for [base](https://github.com/numaproj/numaflow/blob/main/config/namespace-install/kustomization.yaml#L5)

I think this seems okay. I guess we may need to call [GetCommitTreeAtPath()](https://github.com/numaproj-labs/numaplane/blob/main/internal/git/gitsync_processor.go#L340) for the root directory as well as each higher level directory referenced within it.

**Comment by chandankumar4** [comment]
I have went through the [kustomization](https://github.com/kubernetes-sigs/kustomize) and tried to use it as a library to generate the manifest but it didn't worked out, so I was checking how others are using and found out that [argocd run kustomize binary](https://github.com/argoproj/argo-cd/blob/master/util/kustomize/kustomize.go) rather than using it's pkg  inside code to generate the manifest.

**Comment by xdevxy** [comment]
yes, @chandankumar4 they are just using the binary and launch it `as subprocess and dynamically build the YAML file` which is mentioned in this description. Can you please follow their approach? Or maybe we can even reuse their code there?

**Comment by xdevxy** [comment]
In terms of do we want to provide a `Type` field to distinguish between different environments, ArgoCD does do that https://github.com/argoproj/argo-cd/blob/master/docs/operator-manual/application.yaml#L26-L138. So I would image we will need to do the same.

**Comment by juliev0** [comment]
> https://github.com/argoproj/argo-cd/blob/master/docs/operator-manual/application.yaml#L26-L138

I guess in their case they have kustomize-specific fields and helm-specific fields, and so the type is essentially a reference to a struct which may or may not be set to nil. If we think we'll have helm-specific and kustomize-specific parameters in the future (seems quite possible) then we could do the same.

**Comment by whynowy** [comment]
There's a way to use kustomize as a lib, but using it as a binary is also fine (I guess this way might be better since Argo CD takes this approach - there must be a reason).


https://github.com/kubernetes-sigs/kustomize/blob/master/ARCHITECTURE.md#kustomize
