### ISSUE TITLE
Filter yaml files after reading the manifest repository

### ISSUE THREAD

**Issue by chandankumar4** [numaproj-labs/numaplane#58]
While reading the manifest from repository, filter the yaml file based on below criteria.
- Filter the files with extension `.yaml` from set of files.
- Filter `Kustomization.yaml` file (If `Kustomization` is fixed name then it can be filtered via file name as well?)

**Comment by juliev0** [comment]
I am kind of thinking maybe we don't filter on name `kustomization.yaml`, but instead we will have an identifier in `RepositoryPath` struct which will identify whether it's a kustomization-type or not.

For this code, let's assume that we only got here if the `RepositoryPath` is set to "raw" type. We can consider that the yaml files could be any type of yaml file, whether it's Kubernetes resource or something else. I'd say once we get the first resource in the file prior to a "---" delimiter, let's try Chandan's apply method with it. If it fails, we assume the entire file does not contain Kubernetes resources, and since this is not explicitly an error maybe we issue a Warn message (or alternatively an Info message). 

How does that sound to you @chandankumar4 ?

**Comment by juliev0** [comment]
> I'd say once we get the first resource in the file prior to a "---" delimiter, let's try Chandan's `ApplyResource()` method with it. If it fails, we assume the entire file does not contain Kubernetes resources...

Actually, we do need to make sure that it failed for the reason that it wasn't a Kubernetes resource...

**Comment by xdevxy** [comment]
If we want to filter based on the extension, we should make sure to filter `.yaml`, `.yml`, `.json` files. As the last two should also be supported. https://kubernetes.io/docs/concepts/overview/working-with-objects/#describing-a-kubernetes-object

**Comment by juliev0** [comment]
> If we want to filter based on the extension, we should make sure to filter `.yaml`, `.yml`, `.json` files. As the last two should also be supported. https://kubernetes.io/docs/concepts/overview/working-with-objects/#describing-a-kubernetes-object

good point
